pathTypes = {
    "handle__publish_qos0": [
        ("Type-1", "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::write,qos,retain)==AuthResult::success)"),
        ("Type-6"),
        ("Type-7", "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::write,qos,retain)==AuthResult::success)",
         "deliver_to_subscribers-----sender->getThreadData()->getSubscriptionStore()->queuePacketAtSubscribers(subtopics,*this);"),
    ],
    "handle__publish_qos1": [
        ("Type-0", "send__puback-----PubAckpubAck(packet_id);", "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::write,qos,retain)==AuthResult::success)",
         "deliver_to_subscribers-----sender->getThreadData()->getSubscriptionStore()->queuePacketAtSubscribers(subtopics,*this);"),
        ("Type-5", "send__puback-----PubAckpubAck(packet_id);", "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::write,qos,retain)==AuthResult::success)"),
        ("Type-6"),
    ],
    "handle__publish_qos2": [
        ("Type-2", "send__pubrec-----PubRecpubRec(packet_id);", "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::write,qos,retain)==AuthResult::success)",
         "deliver_to_subscribers-----sender->getThreadData()->getSubscriptionStore()->queuePacketAtSubscribers(subtopics,*this);"),
        ("Type-3", "send__pubrec-----PubRecpubRec(packet_id);"),
        ("Type-4", "send__pubrec-----PubRecpubRec(packet_id);", "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::write,qos,retain)==AuthResult::success)"),
        ("Type-6"),
    ],
    "handle__publish_qos0_retained": [
        ("Type-1", "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::write,qos,retain)==AuthResult::success)"),
        ("Type-6"),
        ("Type-7", "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::write,qos,retain)==AuthResult::success)",
         "deliver_to_subscribers-----sender->getThreadData()->getSubscriptionStore()->queuePacketAtSubscribers(subtopics,*this);"),
    ],
    "handle__pubrel": [(
        "Type-0",
        "send__pubcomp-----PubComppubcomp(packet_id);",
    ),],
    "handle__subscribe": [
        (
            "Type-0,17",
            "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::subscribe,qos,false)==AuthResult::success)",
            "send__suback-----SubAcksubAck(packet_id,subs_reponse_codes);",
        ),
        (
            "Type-1",
            "send__suback-----SubAcksubAck(packet_id,subs_reponse_codes);",
        ),
        (
            "Type-2,3,4,5,7,8,9,10,11,12,13,14",
            "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::subscribe,qos,false)==AuthResult::success)",
            "sub_add-----deepestNode->addSubscriber(ses,qos);",
            "acl_check-----if(auth.aclCheck(client_id,username,packet.getTopic(),packet.getSubtopics(),AclAccess::read,effectiveQos,packet.getRetain())==AuthResult::success)",
            "deliver-----returnthis->writeMqttPacket(packet);",
            "send__suback-----SubAcksubAck(packet_id,subs_reponse_codes);",
        ),
        (
            "Type-16",
            "acl_check-----if(authentication.aclCheck(sender->getClientId(),sender->getUsername(),topic,subtopics,AclAccess::subscribe,qos,false)==AuthResult::success)",
            "sub_add-----deepestNode->addSubscriber(ses,qos);",
            "send__suback-----SubAcksubAck(packet_id,subs_reponse_codes);",
        ),
    ],
    "handle__connect_cleanStartT": [
        ("Type-0,4,12,16,32,34,38,40", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-1,5,13,17", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-2,14,33,39", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();",
         "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-3,15", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-6,10,35,37", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-7,11", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-8,36", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();",
         "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-9", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-18,22,26,30,41,43,45,47", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-19,23,27,31", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-20,28,42,46", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-21,29", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-24,44", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);"),
        ("Type-25", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();"),
    ],
    "handle__connect_cleanStartF": [
        ("Type-0,4,12,16,32,34,38,40", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-1,5,13,17", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-2,14,33,39", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();",
         "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-3,15", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-6,10,35,37", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-7,11", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-8,36", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();",
         "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-9", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-18,22,26,30,41,43,45,47", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-19,23,27,31", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);"),
        ("Type-20,28,42,46", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver-----returnthis->writeMqttPacket(packet);", "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-21,29", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();", "deliver-----returnthis->writeMqttPacket(packet);",
         "deliver_to_subscribers-----this->removeQueuedClients();"),
        ("Type-24,44", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);"),
        ("Type-25", "send__connack-----ConnAckconnAck(ConnAckReturnCodes::Accepted,sessionPresent);", "deliver_to_subscribers-----this->removeQueuedClients();"),
    ],
    "handle__disconnect": [
        ("Type-0",),
        (
            "Type-1",
            "deliver_to_subscribers-----this->removeQueuedClients();",
        ),
    ],
    "handle__unsubscribe": [
        (
            "Type-1",
            "send__unsuback-----UnsubAckunsubAck(packet_id);",
        ),
        (
            "Type-2",
            "sub_remove-----deepestNode->removeSubscriber(ses);",
            "send__unsuback-----UnsubAckunsubAck(packet_id);",
        ),
    ],
    "handle__ACL_revoke": [(
        "Type-0",
        "acl_revoke-----",
    ),],
}

