config = {
    "handle__connect": "handle__connect",
    "handle__publish": "handle__publish",
    "handle__pubrel": "handle__pubrel",
    "handle__subscribe": "handle__subscribe",
    "handle__unsubscribe": "handle__unsubscribe",
    "handle__disconnect": "handle__disconnect",
    "handle__authorize": "",
    "handle__revoke": "",
    "permission_check": "mosquitto_acl_check",
    "subs": "mosquitto__subhier::subs",
    "RetainedMsg": "mosquitto_db::retains",
    "status": "mosquitto::state",
    "WillMsg": "mosquitto::will",
    "msgQue": "mosquitto_msg_data::inflight+mosquitto_msg_data::queued",
    "msg": "mosquitto::sock",
    "clientID": "mosquitto::id",
    "permission": "Authentication::aclTree",
    "authorization_pub": "MOSQ_ACL_WRITE",
    "authorization_sub": "MOSQ_ACL_SUBSCRIBE",
    "authorization_read": "MOSQ_ACL_READ",
    "authorization_store": "",
    "authorization_load": "",
}